# Import libraries

In [3]:
import pandas as pd
import numpy as np

# Read csv files

In [4]:
conf_add = "../Data/Input/covid_confirmed_usafacts.csv"
deaths_add = "../Data/Input/covid_deaths_usafacts.csv"
popu_add = "../Data/Input/covid_county_population_usafacts.csv"
confirmed = pd.read_csv(conf_add)
deaths = pd.read_csv(deaths_add)
population = pd.read_csv(popu_add)

# Display dataframe

In [5]:
#COVID-19 dataset

confirmed_index = confirmed.set_index(['countyFIPS','State'])

print('Confirmed shape',confirmed_index.shape)

confirmed_index.head()

Confirmed shape (3195, 240)

,,County Name,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,9/6/20,9/7/20,9/8/20,9/9/20,9/10/20,9/11/20,9/12/20,9/13/20,9/14/20,9/15/20
countyFIPS,State,,,,,,,,,,,,,,,,,,,,,
0,AL,Statewide Unallocated,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1001,AL,Autauga County,1,0,0,0,0,0,0,0,0,...,1498,1504,1508,1522,1544,1551,1565,1576,1585,1601
1003,AL,Baldwin County,1,0,0,0,0,0,0,0,0,...,4713,4730,4757,4787,4833,4886,4922,4959,4978,4992
1005,AL,Barbour County,1,0,0,0,0,0,0,0,0,...,777,778,778,778,785,786,792,794,801,806
1007,AL,Bibb County,1,0,0,0,0,0,0,0,0,...,581,583,589,591,594,602,604,607,610,611

In [6]:
deaths_index = deaths.set_index(['countyFIPS','State'])

print('Deaths shape',deaths_index.shape)

deaths_index.head()

Deaths shape (3195, 240)

,,County Name,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,9/6/20,9/7/20,9/8/20,9/9/20,9/10/20,9/11/20,9/12/20,9/13/20,9/14/20,9/15/20
countyFIPS,State,,,,,,,,,,,,,,,,,,,,,
0,AL,Statewide Unallocated,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1001,AL,Autauga County,1,0,0,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,24,24
1003,AL,Baldwin County,1,0,0,0,0,0,0,0,0,...,46,46,46,46,46,47,47,47,47,47
1005,AL,Barbour County,1,0,0,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,7
1007,AL,Bibb County,1,0,0,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,9

In [7]:
population_index = population.set_index(['countyFIPS','State'])

print('Population shape',population_index.shape)

population_index.head()

Population shape (3195, 2)

                            County Name  population
countyFIPS State
0          AL     Statewide Unallocated           0
1001       AL            Autauga County       55869
1003       AL            Baldwin County      223234
1005       AL            Barbour County       24686
1007       AL               Bibb County       22394

# Merging Step 1: merging population df with confirmed df, inner join

In [8]:
merge_1 = population.merge(confirmed)

print('merge_1 shape: ',merge_1.shape)

merge_1.head()

merge_1 shape:  (3194, 243)

,countyFIPS,County Name,State,population,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,...,9/6/20,9/7/20,9/8/20,9/9/20,9/10/20,9/11/20,9/12/20,9/13/20,9/14/20,9/15/20
0,0,Statewide Unallocated,AL,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,55869,1,0,0,0,0,0,...,1498,1504,1508,1522,1544,1551,1565,1576,1585,1601
2,1003,Baldwin County,AL,223234,1,0,0,0,0,0,...,4713,4730,4757,4787,4833,4886,4922,4959,4978,4992
3,1005,Barbour County,AL,24686,1,0,0,0,0,0,...,777,778,778,778,785,786,792,794,801,806
4,1007,Bibb County,AL,22394,1,0,0,0,0,0,...,581,583,589,591,594,602,604,607,610,611

# Converting the merge_1 dataframe to a long format

In [9]:
merge_11 = pd.melt(merge_1, id_vars=['countyFIPS','County Name','State','stateFIPS','population'], 
        var_name='dates', value_name='confirmed_cases')

merge_11_index = merge_11.set_index(['countyFIPS','State','dates']).sort_values(['countyFIPS','State','dates'])

print('merge_1 long format shape:', merge_11_index.shape)

merge_11_index.head()

merge_1 long format shape: (760172, 4)

                                    County Name  stateFIPS  population  \
countyFIPS State dates
0          AK    1/22/20  Statewide Unallocated          2           0
                 1/23/20  Statewide Unallocated          2           0
                 1/24/20  Statewide Unallocated          2           0
                 1/25/20  Statewide Unallocated          2           0
                 1/26/20  Statewide Unallocated          2           0

                          confirmed_cases
countyFIPS State dates
0          AK    1/22/20                0
                 1/23/20                0
                 1/24/20                0
                 1/25/20                0
                 1/26/20                0

# Converting deaths dataframe to long format

In [10]:
deaths_1 = pd.melt(deaths, id_vars=['countyFIPS','County Name','State','stateFIPS'], 
        var_name='dates', value_name='deaths')

deaths_1_index = deaths_1.set_index(['countyFIPS','State','dates']).sort_values(['countyFIPS','State','dates'])

print('Deaths long format shape:',deaths_1_index.shape)

deaths_1_index.head()

Deaths long format shape: (760410, 3)

                                    County Name  stateFIPS  deaths
countyFIPS State dates
0          AK    1/22/20  Statewide Unallocated          2       0
                 1/23/20  Statewide Unallocated          2       0
                 1/24/20  Statewide Unallocated          2       0
                 1/25/20  Statewide Unallocated          2       0
                 1/26/20  Statewide Unallocated          2       0

# Merging Step 2: merging the resultant of step 1 with the deaths df, inner join

In [11]:
merge_final = merge_11.merge(deaths_1)

merge_final = merge_final.sort_values(['countyFIPS','State','dates']).set_index(['countyFIPS','stateFIPS','dates'])

print('Final merge file shape: ',merge_final.shape)

merge_final.head(10)

Final merge file shape:  (756602, 5)

                                        County Name State  population  \
countyFIPS stateFIPS dates
0          2         1/22/20  Statewide Unallocated    AK           0
                     1/23/20  Statewide Unallocated    AK           0
                     1/24/20  Statewide Unallocated    AK           0
                     1/25/20  Statewide Unallocated    AK           0
                     1/26/20  Statewide Unallocated    AK           0
                     1/27/20  Statewide Unallocated    AK           0
                     1/28/20  Statewide Unallocated    AK           0
                     1/29/20  Statewide Unallocated    AK           0
                     1/30/20  Statewide Unallocated    AK           0
                     1/31/20  Statewide Unallocated    AK           0

                              confirmed_cases  deaths
countyFIPS stateFIPS dates
0          2         1/22/20                0       0
                     1/23/20                0       0
                     1/24/20                0       0
                     1/25/20                0       0
                     1/26/20                0       0
                     1/27/20                0       0
                     1/28/20                0       0
                     1/29/20                0       0
                     1/30/20                0       0
                     1/31/20                0       0

# Export file

In [12]:
merge_final.to_csv('../Data/Output/Merged_COVID19_file.csv')